pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        maven {
            url 'https://jfrog.rinoiot.com/artifactory/Rino_app/'
            credentials {
                username 'rino_app'
                password 'RinoIot-.App2023'
            }
        }
        maven { url 'https://linphone.org/maven_repository' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
    }
}

rootProject.name = "FanvilTalkSdkDemo"
include ':app'
include ':fanvil-link-sdk'
